### PR TITLE
Api spec

### PR DESCRIPTION
**Pull request by VanJackal**
added initial api spec

### CODE REVIEW

**Review by kivine99 — CHANGES_REQUESTED** [review]
I think there should be a query parameter in create new deck that takes the name of the deck.

**Comment by VanJackal** [comment]
I think a body would be better, I forgot to add it

**Review by kivine99 — CHANGES_REQUESTED** [review]
I just thought of one more thing we'll need--a path for abilities that gives a description of each one.

**Comment by VanJackal** [comment]
> I just thought of one more thing we'll need--a path for abilities that gives a description of each one.

I think this should be moved to another issue since that is new functionality. We will definitely need it though

**Pull request merged**
